[package]
name = "nostr-sdk"
version = "0.19.1"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
#homepage.workspace = true
#repository.workspace = true
#license.workspace = true
readme = "README.md"
#rust-version.workspace = true
keywords = ["nostr", "sdk", "rust"]

[features]
default = ["all-nips"]
sqlite = ["dep:nostr-sdk-sqlite"]
blocking = ["dep:once_cell", "nostr/blocking"]
vanity = ["nostr/vanity"]
all-nips = ["nip03", "nip04", "nip05", "nip06", "nip11", "nip19", "nip46"]
nip03 = ["nostr/nip03"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip11 = ["nostr/nip11"]
nip19 = ["nostr/nip19"]
nip46 = ["nostr/nip46"]

[dependencies]
futures-util = "0.3"
log = "0.4"
nostr = { version = "0.19", path = "../nostr", default-features = false }
nostr-sdk-sqlite = { version = "0.19", path = "../nostr-sdk-sqlite", optional = true }
once_cell = { version = "1.17", optional = true }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.23"
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"] }
webpki-roots = "0.22"

[dev-dependencies]
env_logger = "0.10"
serde_json = "1.0"

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "client_with_opts"
required-features = ["all-nips"]

[[example]]
name = "sqlite"
required-features = ["all-nips", "sqlite"]

[[example]]
name = "blocking"
required-features = ["all-nips", "blocking"]

[[example]]
name = "nostr_connect"
required-features = ["nip46"]
